export const INIT_NUVEI = 'INIT_NUVEI';
export const INIT_SUCCESS = "INIT_SUCCESS";
export const GENERATE_TOKEN_SUCCESS = "GENERATE_TOKEN_SUCCESS";
export const GENERATE_TOKEN_FAILED = "GENERATE_TOKEN_FAILED";
export const INIT_PAYMENT = 'INIT_PAYMENT';
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAILED = "PAYMENT_FAILED";
